{% set name = "lingua-language-detector" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lingua-language-detector-{{ version }}.tar.gz
  sha256: f39275b6d28b2972c2d1ffdd6d53d7863c2113af6cd2a7a04c3cbbfa00293ef0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - numpy >=1.23.2,<2.0.0
    - regex >=2022.8.17,<2023.0.0

test:
  imports:
    - lingua
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pemistahl.github.io/lingua-py
  summary: An accurate natural language detection library, suitable for long and short text alike
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
